export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const CREATE_JOB_BEGIN = 'CREATE_JOB_BEGIN'
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS'
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR'

export const CREATE_ARTICLE_BEGIN = 'CREATE_ARTICLE_BEGIN'
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS'
export const CREATE_ARTICLE_ERROR = 'CREATE_ARTICLE_ERROR'

export const EDIT_JOB_BEGIN = 'EDIT_JOB_BEGIN'
export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS'
export const EDIT_JOB_ERROR = 'EDIT_JOB_ERROR'

export const EDIT_ARTICLE_BEGIN = 'EDIT_ARTICLE_BEGIN'
export const EDIT_ARTICLE_SUCCESS = 'EDIT_ARTICLE_SUCCESS'
export const EDIT_ARTICLE_ERROR = 'EDIT_ARTICLE_ERROR'

export const GET_JOBS_BEGIN = 'GET_JOB_BEGIN'
export const GET_JOBS_SUCCESS = 'GET_JOB_SUCCESS'

export const GET_ARTICLES_BEGIN = 'GET_ARTICLES_BEGIN'
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS'

export const GET_ARTICLE_BEGIN = 'GET_ARTICLE_BEGIN'
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS'
export const GET_ARTICLE_ERROR = 'GET_ARTICLE_ERROR'

export const GET_COMMENTS_BEGIN = 'GET_COMMENTS_BEGIN'
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS'
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR'

export const GET_LIKES_BEGIN = 'GET_LIKES_BEGIN'
export const GET_LIKES_SUCCESS = 'GET_LIKES_SUCCESS'
export const GET_LIKES_ERROR = 'GET_LIKES_ERROR'

export const GET_UNLIKES_BEGIN = 'GET_UNLIKES_BEGIN'
export const GET_UNLIKES_SUCCESS = 'GET_UNLIKES_SUCCESS'
export const GET_UNLIKES_ERROR = 'GET_UNLIKES_ERROR'

export const CREATE_COMMENTS_BEGIN = 'CREATE_COMMENTS_BEGIN'
export const CREATE_COMMENTS_SUCCESS = 'CREATE_COMMENTS_SUCCESS'
export const CREATE_COMMENTS_ERROR = 'CREATE_COMMENTS_ERROR'

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN'
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'

export const SHOW_ARTICLES_BEGIN = 'SHOW_ARTICLES_BEGIN'
export const SHOW_ARTICLES_SUCCESS = 'SHOW_ARTICLES_SUCCESS'

export const SHOW_ARTICLES_COMMENTS_BEGIN = 'SHOW_ARTICLES_COMMENTS_BEGIN'
export const SHOW_ARTICLES_COMMENTS_SUCCESS = 'SHOW_ARTICLES_COMMENTS_SUCCESS'

export const SHOW_ALL_ARTICLES_BEGIN = 'SHOW_ALL_ARTICLES_BEGIN'
export const SHOW_ALL_ARTICLES_SUCCESS = 'SHOW_ALL_ARTICLES_SUCCESS'

export const SET_EDIT_JOB = 'SET_EDIT_JOB'
export const SET_EDIT_ARTICLE = 'SET_EDIT_ARTICLE'

export const DELETE_JOB_BEGIN = 'DELETE_JOB_BEGIN'
export const DELETE_JOB_ERROR = 'DELETE_JOB_ERROR'

export const DELETE_COMMENT_BEGIN = 'DELETE_COMMENT_BEGIN'
export const DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR'

export const DELETE_POST_BEGIN = 'DELETE_POST_BEGIN'
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR'


export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const LOG_OUT = 'LOG_OUT'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES' 
export const CLEAR_FILTERS = 'CLEAR_FILTERS'

export const CHNAGE_PAGE = 'CHANGE_PAGE'